version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase
    cooldown:
      default-days: 1
    commit-message:
      prefix: build
      prefix-development: build
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
